version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alta
      POSTGRES_PASSWORD: alta
      POSTGRES_DB: alta
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

